
#Jobs = Job.create([{title: 'Business Analyst', jobDescription: "This is all about the job and what you'll be working on.", personalSpec: 'These are the qualities for which you must have.', selectDetails: 'During the application stage a presentation will be required', contractType: 'Permanent', workingPattern: 'Full Time', salaryMin: 26000, salaryMax: 34291}])
#Job.create([{title: 'Commercial manager', jobDescription: "This is all about the job and what you'll be working on.", personalSpec: 'These are the qualities for which you must have.', selectDetails: 'During the application stage a presentation will be required', contractType: 'Permanent', workingPattern: 'Part Time', salaryMin: 26000, salaryMax: 31291}])
#Job.create([{title: 'Front-end developer', jobDescription: "This is all about the job and what you'll be working on.", personalSpec: 'These are the qualities for which you must have.', selectDetails: 'During the application stage a presentation will be required', contractType: 'Permanent', workingPattern: 'Full Time', salaryMin: 26000, salaryMax: 24291}])

#Departments = Department.create([{name: "HM Revenue and Customs",logo: "tbc"}])
#Department.create([{name: "Department for Work and Pensions",logo: "tbc"}])
#Department.create([{name: "Home Office",logo: "tbc"}])
#Department.create([{name: "Ministry of Defence",logo: "tbc"}])

#Users = User.create([{firstname: "Mark", lastname:"williams", email: "mark.developing@gmail.com", password: "mark", password_confirmation: "mark", department_id: 1, activated: true, activated_at: Time.zone.now}])

#Grades = Grade.create([{grade: "Administrative Assistant"}])
#Grade.create([{grade: "Administrative Officer"}])
#Grade.create([{grade: "Executive Officer"}])
#Grade.create([{grade: "Higher Executive Officer"}])
#Grade.create([{grade: "Senior Executive Officer"}])
#Grade.create([{grade: "Grade 7"}])
#Grade.create([{grade: "Grade 6"}])
#Grade.create([{grade: "SCS Pay Band 1"}])
#Grade.create([{grade: "SCS Pay Band 2"}])
#Grade.create([{grade: "SCS Pay Band 3"}])
#Grade.create([{grade: "Industrial"}])
#Grade.create([{grade: "Other"}])

Status.create([{name: "Job advert incomplete"}])
Status.create([{name: "Awaiting approval"}])
Status.create([{name: "Advetised internally"}])
Status.create([{name: "Advertised externally"}])
Status.create([{name: "Advertised across CS"}])
Status.create([{name: "Advertised externally"}])
Status.create([{name: "Closed for applications"}])
Status.create([{name: "Archived"}])

#Countries = Country.create([{name:"England"}])
#Country.create([{name:"Scotland"}])
#Country.create([{name:"Wales"}])
#Country.create([{name:"Northern Ireland"}])
#Country.create([{name:"Overseas"}])

#Contracts = Contract.create([{contract: 'Permanent'}])
#Contract.create([{contract: 'Temporary'}])
#Contract.create([{contract: 'Fixed Term Appointment'}])
#Contract.create([{contract: 'Loan'}])

#Work_patterns = WorkPattern.create([{working_pattern: 'Full Time'}])
#WorkPattern.create([{working_pattern: 'Part Time'}])
#WorkPattern.create([{working_pattern: 'Job Share'}])
#WorkPattern.create([{working_pattern: 'Flexible Working'}])

#Regions = Region.create([{name: "South West"}])
#Region.create([{name: "South East"}])
#Region.create([{name: "London"}])
#Region.create([{name: "North West"}])
#Region.create([{name: "East of England"}])
#Region.create([{name: "West Midlands"}])
#Region.create([{name: "Yorkshire and the Humber"}])
#Region.create([{name: "East Midlands"}])
#Region.create([{name: "North East"}])
#Region.create([{name: "Northern Ireland"}])
#Region.create([{name: "Scotland"}])
#Region.create([{name: "Wales"}])